ТЗ-11
necron33rus/java-filmorate pull request #4
Opened 2023-06-09 23:35 UTC by necron33rus

схема БД + таблицы - в файле readme.md

2023-06-10 17:51 UTC, Frilock requested changes
Добрый день, по работе, у меня претензия по работе со слоями приложения, кроме того, оставил еще ряд комментариев

2023-06-10 17:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Вроде уже обсуждали этот момент, что в слое контроллера не должны игжектиться бины хранилищ, то есть все методы storage которые вы тут используете надо перенести в сервис и вызывать тут уже сервис

2023-06-10 17:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Аналогично

2023-06-10 17:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public GenreService(GenreStorage genreStorage) {
Вы же добавили аннотацию @RequiredArgsConstructor - зачем вам конструктор?

2023-06-10 17:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private final RatingService ratingService;
В слое хранилищ вы не должны вызывать слой сервиса, иначе можете получить циклическую зависимость

2023-06-10 17:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (rows.first()) {
Можно инвертировать условие и тогда вы избавитесь от лишней вложенности

2023-06-10 17:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public void deleteFilm(Long filmId) {
Если реализация тот или иной метод не поддерживает, принято какое то исключение бросать внутри, чтобы не вводило в заблуждение

2023-06-10 17:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/friends/FriendsStorage.java
> +        } else if (userStorage.getUserById(userId) != null) {
Вообще userStorage.getUserById(userId) != null лучше сделать какую то обертку над методом, чтобы по названию было понятно что вы проверяете наличие объекта в БД, а так вы просто поиск выполняете - например, checkUserExist или что то такое

2023-06-10 17:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreStorage.java
> +        if (name == null) {
Лучше проверять через StringUtils.isBlank. Или пустая строка допускается?

2023-06-10 17:51 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> -
А почему тесты удалили? По идее ничего не должно меняться, вы же просто БД прикрутили вместо хранения в памяти

2023-06-10 17:51 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
По идее должно работать и без onConstructor_ = @Autowired

2023-06-10 17:51 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +        firstFilm = filmStorage.createFilm(firstFilm);
А какой смысл перед каждым тестов в     public void beforeEach()  создавать все эти обьекты и потом в каждом тесте создавать их снова?

2023-06-11 12:48 UTC, necron33rus commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
+

2023-06-11 12:51 UTC, necron33rus commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
done

2023-06-11 12:52 UTC, necron33rus commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public GenreService(GenreStorage genreStorage) {
done

2023-06-11 13:00 UTC, necron33rus commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public void deleteFilm(Long filmId) {
done

2023-06-11 13:02 UTC, necron33rus commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreStorage.java
> +        if (name == null) {
done

2023-06-11 21:25 UTC, necron33rus commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private final RatingService ratingService;
done

2023-06-11 21:41 UTC, necron33rus commented on src/main/java/ru/yandex/practicum/filmorate/storage/friends/FriendsStorage.java
> +        } else if (userStorage.getUserById(userId) != null) {
done

2023-06-11 22:07 UTC, necron33rus commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (rows.first()) {
done

2023-06-11 22:12 UTC, necron33rus commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
![Снимок экрана 2023-06-12 в 01 10 46](https://github.com/necron33rus/java-filmorate/assets/19770977/39e17b20-ed17-4311-9fe4-9b4aca23931a)

в ТЗ так

2023-06-11 22:45 UTC, necron33rus commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +        firstFilm = filmStorage.createFilm(firstFilm);
действительно))) тупанул ночью(

2023-06-12 00:05 UTC, necron33rus commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> -
done

2023-06-12 00:12 UTC, necron33rus commented
ага...надо получше поизучать слои..

2023-06-12 08:22 UTC, Frilock requested changes
Добрый день, пара совсем маленьких комментариев, и можно принимать.
Еще попрошу вас обратить внимание, на конструкцию if - else. Довольно много где ее у вас можно упростить, оставив, например, только блок if. Это не критично, но возможно упростит ваш код

2023-06-12 08:22 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
В ваших методах ниже, везде лишний блок else, поскольку в блоке if вы вызываете return

2023-06-12 08:22 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    @Autowired
Аннотация не нужна, нужно поле сделать final. Поскольку у вас над классом висит @RequiredArgsConstructor

2023-06-12 08:22 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/RatingService.java
> +    @Autowired
Давайте придерживаться одного стиля, где то вы делаете конструктор руками, а где то используете RequiredArgsConstructor. Давайте выберем что то одно

2023-06-12 15:49 UTC, necron33rus commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    @Autowired
done

2023-06-12 15:58 UTC, necron33rus commented on src/main/java/ru/yandex/practicum/filmorate/service/RatingService.java
> +    @Autowired
done

2023-06-12 16:19 UTC, necron33rus commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
done

2023-06-12 16:25 UTC, necron33rus commented
да, в каникулы посмотрю и оптимизируюсь по условиям if-else

2023-06-12 20:11 UTC, Frilock approved these changes
Принято

2023-06-13 07:46 UTC, merged